name: Ptr CI

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.24.x
      uses: actions/setup-go@v6
      with:
        go-version: 1.24.x
        cache-dependency-path: go.sum

    - name: Checkout Code
      uses: actions/checkout@v5

    - name: go-fmt
      run: |
        if [ -n "$(gofmt -s -l .)" ]; then
          echo "Go code is not formatted, run 'gofmt -s -w .'"
          exit 1
        fi

    - name: go-vet
      run: go vet ./...

  test:
    name: Test
    needs: check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Set up Go 1.24.x
      uses: actions/setup-go@v6
      with:
        go-version: 1.24.x
        cache-dependency-path: go.sum

    - name: Test Keycloak
      run: go test -race -v -coverprofile=coverage.txt ./...

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}